### GET all albums
GET http://localhost:8080/webapi/albums

### GET album by id
GET http://localhost:8080/webapi/albums/1
Accept: application/xml

### GET album with params
GET http://localhost:8080/webapi/albums?phrase=abc
custom-header: custom-value
Cookie: some-cookie=some-value

### GET albums playing track
GET http://localhost:8080/webapi/tracks/1/albums
Accept: application/json

### create new album
POST http://localhost:8080/webapi/albums
Content-Type: application/json
Accept-Language: ja

## Integer w klasach by bylo bez "id" w json
{
  "id": 0,
  "name": "12",
  "logo": "123"
}


### get all tracks
GET http://localhost:8080/webapi/tracks

### get track by id
GET http://localhost:8080/webapi/tracks/1

### get tracks in album
GET http://localhost:8080/webapi/albums/1/tracks

### create new track
POST http://localhost:8080/webapi/tracks
Content-Type: application/json

{
  "id": 0,
  "title": "IO",
  "artist": { "id": 1 },
  "duration": 130
}

###
##private String title
##private Artist artist
##private int duration
