### GET all albums
GET http://localhost:8080/webapi/albums

### GET album by id
GET http://localhost:8080/webapi/albums/1
Accept: application/json

### GET album with params
GET http://localhost:8080/webapi/albums?phrase=foo
custom-header: custom-value
Cookie: some-cookie=some-value

### GET albums playing track
GET http://localhost:8080/webapi/tracks/1/albums
Accept: application/json

### create new album
POST http://localhost:8080/webapi/albums
Content-Type: application/json
Accept-Language: ja

## Integer w klasach by bylo bez "id" w json
{
  "name": "12",
  "logo": "123"
}


### get all tracks
GET http://localhost:8080/webapi/tracks

### get track by id
GET http://localhost:8080/webapi/tracks/1

### get tracks in album
GET http://localhost:8080/webapi/albums/1/tracks

### create new track
POST http://localhost:8080/webapi/tracks
Content-Type: application/json

{
  "title": "IO",
  "artistId": 10,
  "duration": 130
}